### ISSUE TITLE
Missing main file?

### ISSUE THREAD

**Issue by ArvinJA** [nickbabcock/jomini#2]
```
module.js:440
    throw err;
    ^

Error: Cannot find module './lib/jomini'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Arvin\AppData\Roaming\npm\node_modules\jomini\index.js:2:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```
And yeah, in the lib folder there's no "jomini.js" file, as one would expect.

**Comment by nickbabcock** [comment]
Haha, yeah I just noticed that. I'll have to look up if there is a standard way uploading compiled js to npm, and I'll release another version.

**Comment by nickbabcock** [comment]
Just released 0.2.4 which should fix the problem :smile: 

Sorry about that.

**Comment by ArvinJA** [comment]
Perfect, thanks, I really didn't expect an update so fast :)

**Comment by nickbabcock** [comment]
No problem! Happy to help
